version: '2'
services:
    web:
        build: .
        command: handler.py
        expose:
            - "5000"
        ports:
            - "5000:5000"
        depends_on:
            - db
    db:
        image: postgres
